name = "imb-website"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "imb-submissions"
database_id = "59479035-d13f-4109-9497-defd4c0eddea"